### PR TITLE
Add new search widget for Content View and new host page

### PR DESCRIPTION
**Pull request by jameerpathan111**
Add support for new search bar present on Content view and new host details page.

Refer:
https://github.com/SatelliteQE/airgun/pull/656

### CODE REVIEW

**Comment by jameerpathan111** [comment]
@latran you can use this pr's code to unblock search issue you are facing on content view page.
We can figure out issue related to `self.table.read()` later, currently I am using `time.sleep(3)` as a workaround.

**Comment by latran** [comment]
FYI, the `contenview.py` in both `entities` and `view` should remain the same for the old cv.  I have a draft PR for the new ones.

**Comment by jameerpathan111** [comment]
> FYI, the `contenview.py` in both `entities` and `view` should remain the same for the old cv. I have a draft PR for the new ones.

@latran 
Yes, the code change I did in `contenview.py` was just for my testing and for your reference, I will revert that later.
Also, I tried `table = PatternflyTable(component_id='OUIA-Generated-Table-2')` like you had mentioned in your pr, but that
didn't work. The `component_id` of table was different after performing search operation, you will have to look for a better 
locator. You can try `table = PatternflyTable(locator='.//table[@data-ouia-component-type="PF4/Table"]')` but this
one is also not that robust.

**Comment by latran** [comment]
@jameerpathan111 I've noticed that as well.  I will try the old table and some new locator for the new table and see.

**Pull request closed without merging**
