### PR TITLE
Update Global Registration OUIA IDs

### PR DESCRIPTION
**Pull request by shweta83**
OUIA IDs of Global Registration are updated and it is causing failures in stream. This change only impacts stream.

### CODE REVIEW

**Review by lhellebr — APPROVED** [review]
Are these changes in product permanent and intentional? If yes and if the tests pass, ACK.

**Review by sambible — APPROVED** [review]
ACK pending some results showing this working in regular Satellite as well. I will say, this is far superior to the locators we were using previously, assuming these ouia IDs are in the product. Those previous one only worked because nothing else would ever use those same tags above those elements in the page :confused:

**Comment by shweta83** [comment]
> Are these changes in product permanent and intentional? If yes and if the tests pass, ACK.

Since these changes are only in stream so I cannot say in confidence if it is permanent but this change will help with the PRT running on master and E2E test cases as well.

**Comment by shweta83** [comment]
> ACK pending some results showing this working in regular Satellite as well. I will say, this is far superior to the locators we were using previously, assuming these ouia IDs are in the product. Those previous one only worked because nothing else would ever use those same tags above those elements in the page 😕

If you mean regular as 6.14.0 then No, this change currently impacts stream only.

**Comment by omkarkhatavkar** [comment]
@shweta83 can you run some tests here using PRT?

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_positive_global_registration_form

**Comment by omkarkhatavkar** [comment]
PRT passed!

**Pull request merged**
