### PR TITLE
updating to more accurate table locator

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
There is one new more table was added in view. hence updated table locator.

### Test Resut 

Testing started at 4:39 PM ...
/home/okhatavk/Satellite/robottelo/env/bin/python /home/okhatavk/Downloads/pycharm-community-2018.1.4/helpers/pycharm/_jb_pytest_runner.py --target test_dashboard.py::test_positive_task_status
Launching py.test with arguments test_dashboard.py::test_positive_task_status in /home/okhatavk/Satellite/robottelo/tests/foreman/ui

2019-07-29 16:39:26 - conftest - DEBUG - Registering custom pytest_configure

2019-07-29 16:39:26 - conftest - DEBUG - Fetching BZs to deselect...

2019-07-29 16:40:20 - conftest - DEBUG - Deselected tests reason: BZ resolution ['1347658', '1475443', '1214312', '1414821', '1226425', '1217635', '1147100', '1230902', '1311113', '1199150', '1278917', '1310422', '1204686', '1156555', '1487317', '1479291']

2019-07-29 16:40:20 - conftest - DEBUG - Deselected tests reason: missing version flag ['1610309', '1347658', '1701118', '1475443', '1682940', '1194476', '1214312', '1226425', '1217635', '1147100', '1230902', '1311113', '1199150', '1278917', '1310422', '1436209', '1701132', '1716429', '1204686', '1156555', '1378442', '1489322', '1625783', '1581628', '1487317', '1479291']

2019-07-29 16:40:20 - conftest - DEBUG - Deselected tests reason: sat-backlog ['1610309', '1347658', '1701118', '1475443', '1682940', '1194476', '1214312', '1226425', '1217635', '1147100', '1230902', '1311113', '1199150', '1278917', '1310422', '1436209', '1701132', '1716429', '1204686', '1156555', '1378442', '1489322', '1625783', '1581628', '1487317', '1479291']

============================= test session starts ==============================
platform linux -- Python 3.4.8, pytest-4.0.2, py-1.7.0, pluggy-0.9.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: xdist-1.26.1, services-1.3.1, mock-1.10.0, forked-1.0.2, cov-2.6.12019-07-29 16:40:21 - conftest - DEBUG - Collected 1 test cases

collected 1 item

test_dashboard.py                                                       [100%]

========================== 1 passed in 178.47 seconds

### CODE REVIEW

**Comment by vijay8451** [comment]
@omkarkhatavkar as per tests you are fixing it for `test_dashboard.py::test_positive_task_status` ... when checked the Airgun it related to this , please check.
https://github.com/SatelliteQE/airgun/blob/51a0f29cf768b637819a3bc163d3aaff2dbca1f8/airgun/views/dashboard.py#L116

**Comment by omkarkhatavkar** [comment]
@vijay8451 It was failing at location https://github.com/SatelliteQE/robottelo/blob/b1d409985a7938c7c593495c5532e5cc8abac60f/tests/foreman/ui/test_dashboard.py#L222. Where it is going through task entity.  Can you please take a look again.

**Comment by omkarkhatavkar** [comment]
@vijay8451 Here it is the new UI I was talking about 
AwesomeScreenshot-Tasks-2019-07-29-17-07-63

**Comment by vijay8451** [comment]
@omkarkhatavkar ahh got it ... I just saw we another related issue raised by @pondrejk here: https://github.com/SatelliteQE/robottelo/issues/7220 with PR: https://github.com/SatelliteQE/airgun/pull/376 please take a look.

**Comment by omkarkhatavkar** [comment]
@vijay8451 #duplicate work :) I will withdraw the changes

**Pull request closed without merging**
