### PR TITLE
ids for SyspurposeBulkActionView

### PR DESCRIPTION
**Pull request by pondrejk**
requested IDs landed within https://bugzilla.redhat.com/show_bug.cgi?id=1931527 modifying the view accordingly

### CODE REVIEW

**Review by lhellebr — COMMENTED** [review]
LGTM, can you paste results of some test using it?

**Review by jameerpathan111 — APPROVED** [review]
ACK

**Comment by pondrejk** [comment]
@lhellebr 
```
pytest tests/foreman/ui/test_contenthost.py -k test_syspurpose_bulk_action
================================================= test session starts =================================================

tests/foreman/ui/test_contenthost.py .                                                                          [100%]

============================== 1 passed, 28 deselected in 109.22 s  ===================================
```

**Comment by pondrejk** [comment]
@lhellebr @jameerpathan111 can we please get this in before the next automation run?

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Pull request merged**
