### PR TITLE
Scap contentview title fixed

### PR DESCRIPTION
**Pull request by vijaysawant**
small fix in the heading of page

### CODE REVIEW

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_oscapcontent.py::test_external_disa_scap_content

**Review by adarshdubey-star — APPROVED** [review]
LGTM

**Review by shubhamsg199 — APPROVED** [review]

**Comment by adarshdubey-star** [comment]
Do we need this in 6.13 @vijaysawant ?

**Comment by vijaysawant** [comment]
> Do we need this in 6.13 @vijaysawant ?

Yes, @adarshdubey-star

**Pull request merged**
