### PR TITLE
[6.15.z] Check that breadcrumb is displayed

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1281

error occurred in 6.15.z

### CODE REVIEW

**Review by LadislavVasina1 — CHANGES_REQUESTED** [review]
In my opinion, this does totally nothing. 
Correct me if I am wrong.
It just returns bool and nothing is done with it.

**Comment by dosas** [comment]
@LadislavVasina1 That is not correct it does not do nothing, it waits for the element to be displayed.

No, it makes much more sense to use the abstraction. That is why it is there.

**Comment by LadislavVasina1** [comment]
@dosas exception false is just from this implementation, that your implementation actual uses https://github.com/SatelliteQE/airgun/blob/7995b52325eac8696bb49d2618458f82839ca88e/airgun/views/contenthost.py#L122-L134 
See: https://github.com/SatelliteQE/airgun/pull/1281#issuecomment-2006539110

**Comment by LadislavVasina1** [comment]
exception false is set because you want to get True or False from this property and do with this information whatever you want

**Comment by dosas** [comment]
Closed in favor of https://github.com/SatelliteQE/airgun/pull/1299

**Pull request closed without merging**
