### PR TITLE
call done.click() if via Katello Agent (#331)

### PR DESCRIPTION
**Pull request by swadeley**
Proposing an if statement to close the Update Packages dialogue. I did try an else statement at the end but got errors.

Edit: I found this was required while working on https://github.com/SatelliteQE/robottelo/pull/6974

### CODE REVIEW

**Comment by swadeley** [comment]
Hello

The `manage_packages()` function is used a number of times in `test_hostcollection.py`. But here we are only interested in those that do not use `action_via` (so that it defaults to using katello agent). I see  `test_positive_install_package` is a test without `action_via`. That test passes.

I then ran a test using the complete `tests/foreman/ui_airgun/test_hostcollection.py` file. All test pass except `test_positive_install_errata` which does not use, does not call, `manage_packages()`.  I think that could be caused by the bug mentioned in https://github.com/SatelliteQE/robottelo/pull/6974. I will apply the update and test again.

**Comment by mirzal** [comment]
@swadeley I think it will be enough if you add output of something like:
```
pytest -v -k 'test_positive_install_package or test_positive_remove_package' tests/foreman/ui_airgun/test_hostcollection.py
```

I mean, it's patch adding two lines, it should have been merged already. Let's not make it longer and harder than necessary.

**Comment by swadeley** [comment]
robottelo]$ pytest -v tests/foreman/ui_airgun/test_hostcollection.py::test_positive_install_package
============================== test session starts =============================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.8.0, pluggy-0.12.0 -- .virtualenvs/robottelo-master/bin/python3
cachedir: .pytest_cache
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo, inifile:
plugins: services-1.3.1, forked-1.0.2, xdist-1.28.0, cov-2.7.1, mock-1.10.0
collecting ... 2019-06-04 06:17:11 - conftest - DEBUG - BZ deselect is disabled in settings

collected 1 item                                                                                        

tests/foreman/ui_airgun/test_hostcollection.py::test_positive_install_package PASSED              [100%]

======================== 1 passed, 2 warnings in 662.97 seconds ===================

**Comment by swadeley** [comment]
thank you @mirzal

**Comment by oshtaier** [comment]
@mirzal It doesn't matter how many lines we have in PR, if you change basic framework, it is required to provide test result

**Pull request merged**
