### PR TITLE
updated locator to fetch the datastore

### PR DESCRIPTION
**Pull request by amolpati30**

### CODE REVIEW

**Review by sambible — CHANGES_REQUESTED** [review]
Can we get a description of the need for this change? Seems unnecessary, so I'm a bit confused. Passing PRT would be good as well, on a test utilizing this.

**Comment by LadislavVasina1** [comment]
@amolpati30 Any updates on this PR?

**Comment by amolpati30** [comment]
> @amolpati30 Any updates on this PR?



> @amolpati30 Any updates on this PR?

**Comment by amolpati30** [comment]
> @amolpati30 Any updates on this PR?

I created this PR to verify whether the [issue](https://github.com/SatelliteQE/robottelo/pull/16507) is resolved, but despite trying multiple changes, it is still failing while creating the compute profile. I believe the locator is not the cause of the issue, so I am closing this PR.

**Comment by LadislavVasina1** [comment]
@amolpati30 Any updates on this PR?

**Comment by amolpati30** [comment]
@LadislavVasina1 You can go ahead and merge this; it is ready, and the PRTs were passing in Robottelo.

**Pull request closed without merging**
