### PR TITLE
Removing all elements of puppet modules from view and entities file

### PR DESCRIPTION
**Pull request by latran**
Puppet module removal from views and entities section.

### CODE REVIEW

**Review by omkarkhatavkar — CHANGES_REQUESTED** [review]
Can you please add the PR to  remove tests from robottelo, If already done? please mentioned the merged PR here?

**Review by omkarkhatavkar — COMMENTED** [review]
Linking the puppet PR's still in pending status : 

https://github.com/SatelliteQE/robottelo/pull/8743
https://github.com/SatelliteQE/robottelo/pull/8741
https://github.com/SatelliteQE/robottelo/pull/8744

**Review by omkarkhatavkar — APPROVED** [review]

**Comment by jameerpathan111** [comment]
@latran we shouldn't remove this code because we will need it for upgrade marker testes. Refs: https://github.com/SatelliteQE/robottelo/pull/8743#discussion_r663890459
For ex. `test_positive_add_puppet_module` ui test.

**Comment by latran** [comment]
Hey @jameerpathan111 and @omkarkhatavkar , 

@tstrych , @vsedmik , and I will be working together to assess all test cases that has puppet and would fall under upgrade marker with @devendra104 .  Some will be obsolete while others will be slightly modified.  This will also affect those 3 corresponding puppet PRs as well this one.  For now, I'll put this back on draft with `do_not_merge` label until all assessments have been finalized.

**Comment by tstrych** [comment]
@jameerpathan111 `test_positive_add_puppet_module` is no longer possible to test with upgrade or without upgrade marker.
Once you upgrade the satellite there is no longer possible to create a repository with `puppet` content type. 

https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/ui/test_lifecycleenvironment.py#L129
Also `add_puppet_module` same test L135  uses `SelectPuppetModuleVersion` https://github.com/SatelliteQE/airgun/blob/master/airgun/entities/contentview.py#L99 which is no longer in content view in sat 6.10

**Review by jameerpathan111 — APPROVED** [review]

**Review by pondrejk — APPROVED** [review]

**Pull request merged**
