### PR TITLE
Fix GR and current user OUIA ids

### PR DESCRIPTION
**Pull request by shweta83**

### CODE REVIEW

**Review by omkarkhatavkar — APPROVED** [review]

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_host.test_global_registration_form_populate

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_global_registration_form_populate

**Comment by Gauravtalreja1** [comment]
@shweta83 Can you please rebase and resolve the merge conflicts?

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_global_registration_form_populate

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_host_facts_upload_on_host_registration

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_rhcloud_insights.py -k test_insights_registration_with_capsule

**Review by Gauravtalreja1 — APPROVED** [review]

**Pull request merged**
