### PR TITLE
Download manager fix

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by oshtaier** [comment]
Please provide reasons for that change and test result to prove that change is fixing things.

**Comment by mirzal** [comment]
I can confirm that on Chrome 73, which is not even the latest version, these objects already have `fileUrl` instead of `file_url`. So yeah, if it's not needed yet, it will be eventually.

But we need to somehow coordinate it with upgrade of Chrome that automation uses. Is there any task for that anywhere? Something that we could subscribe to, to be in the loop? Or @lhellebr , are you going to keep track of that and follow up here when right time comes?

**Comment by oshtaier** [comment]
yeap, we have to have static browser version as we usually did in the past, so we do not get completely different results for different environments. Let's say that Jenkins environment should be an example for everyone.

**Comment by lhellebr** [comment]
@mirzal , this is a  change we can do anytime in Jenkins. Also, doing it will cause some tests to fail until this PR is merged. So it's up to us (as in all automation stakeholders).

**Comment by lhellebr** [comment]
```
$ pytest test_reporttemplates.py
========================================= test session starts ==========================================
platform linux -- Python 3.6.8, pytest-3.6.1, py-1.7.0, pluggy-0.6.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo, inifile:
plugins: services-1.3.0, mock-1.10.0
collecting 5 items                                                                                     2019-05-23 15:39:58 - conftest - DEBUG - Collected 5 test cases

collected 5 items                                                                                      

test_reporttemplates.py sss..                                                                    [100%]

================================ 2 passed, 3 skipped in 527.09 seconds =================================
```

**Comment by oshtaier** [comment]
So that PR will fix code for your version of Chrome, but instead make fail tests on mine? I don't mind to move on newer version, but that will require some global re-test. If we all agreed to move, I will ACK that PR on 110%

**Comment by lhellebr** [comment]
Exactly, that's why I said this should have been a Draft PR and I don't expect it to be merged unless we decide to use newer Chrome in automation.

**Comment by oshtaier** [comment]
okay, sorry then =)

**Comment by tstrych** [comment]
This PR should be closed, change was already merged in [this PR](https://github.com/SatelliteQE/airgun/pull/405)

**Comment by lhellebr** [comment]
Right, Tomas's PR should solve the issue. Closing.

**Pull request closed without merging**
