### PR TITLE
Fix for urlencoded addresses, e.g. %20->space

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
```
$ pytest tests/foreman/ui/test_reporttemplates.py::test_positive_generate_entitlements_report
====================================== test session starts ======================================
platform linux -- Python 3.6.9, pytest-4.6.3, py-1.7.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/lhellebr/git/robottelo
plugins: services-1.3.1, mock-1.10.4
collecting ... 2020-02-06 10:43:41 - conftest - DEBUG - Collected 1 test cases
2020-02-06 11:43:42 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f0da7df9a90
2020-02-06 11:43:42 - robottelo.ssh - INFO - Connected to [dhcp-2-143.vms.sat.rdu2.redhat.com]
2020-02-06 11:43:42 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-02-06 11:43:44 - robottelo.ssh - INFO - <<< stdout
satellite-6.7.0-5.beta.el7sat.noarch

2020-02-06 11:43:44 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f0da7df9a90
2020-02-06 11:43:44 - robottelo.host_info - DEBUG - Host Satellite version: 6.7
2020-02-06 11:43:44 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 1 item                                                                                

tests/foreman/ui/test_reporttemplates.py .                                                [100%]

================================== 1 passed in 324.08 seconds ===================================
```

**Comment by vijay8451** [comment]
ACK .. however I am unable to find UI test `test_positive_generate_entitlements_report` am i missing something ?

**Comment by mirekdlugosz** [comment]
@vijay8451 you are right, we have that test for API and CLI, but not UI. I guess this is new test Lukas is working on. And that would also answer my question, I actually must have run other test in my PR.

**Comment by lhellebr** [comment]
Exactly.

**Comment by lhellebr** [comment]
Since this didn't get merged, some conflicts appeared. I've resolved them. Let's merge?

**Pull request merged**
