### PR TITLE
Cherry-picking Ansible UI fixes

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Ansible UI Fixes
https://github.com/SatelliteQE/airgun/pull/790

### CODE REVIEW

**Comment by Griffin-Sullivan** [comment]
This is open against 6.12.z branch. Should we update the label from 6.11 to 6.12?

**Comment by adarshdubey-star** [comment]
> This is open against 6.12.z branch. Should we update the label from 6.11 to 6.12?

I want this to be cherry picked in 6.11.z

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_ansible_custom_role

**Comment by adarshdubey-star** [comment]
Weird,  individually this test case passed as well as on my local setup.

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible

**Comment by adarshdubey-star** [comment]
The reason the whole module is not working together is an issue that I have identified as the entire module is using the same worker and when it's assigning the ansible_role_id as `target_host.assign_ansible_roles(data={'ansible_role_ids': [1]})` with this line over here, there is a clash of not having the same id as 1, it will be changed when running the other test case on the same worker.

**Comment by adarshdubey-star** [comment]
Merging can be performed

**Pull request merged**
