### PR TITLE
Added RHAI Plan

### PR DESCRIPTION
**Pull request by quarckster**
In this PR I implemented create, update and delete methods for RHAI Plan entity.

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@abalakh @oshtaier since I'm not up to speed with airgun, I'll leave this review in your capable hands!

**Comment by oshtaier** [comment]
should I close this PR in favor of https://github.com/SatelliteQE/airgun/pull/181?
I almost did that, but there are some unique changes here

**Comment by quarckster** [comment]
@oshtaier I've changed the PR and left only RHAI Plan related code.

**Comment by quarckster** [comment]
dear @oshtaier could you please find time to review this PR. Thank you so much in advance.

**Pull request merged**
