### PR TITLE
Errata install, and legacy chost methods

### PR DESCRIPTION
**Pull request by damoore044**
Supports robottelo [#15085](https://github.com/SatelliteQE/robottelo/pull/15085)
- Add option to install errata to multiple/all hosts listed, in ContentTypes > Errata > details > ContentHosts tab
- Fix legacy chost errata install and package search methods, to use `LegacyDetails` page
- Some locators updated

### CODE REVIEW

**Review by omkarkhatavkar — APPROVED** [review]
Nice Work !

**Comment by damoore044** [comment]
```
Build Number: 7379
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_errata.py --external-logging
Test Result : ========== 17 passed, 1 skipped, 1903 warnings in 5765.51s (1:36:05) ===========
```

**Review by vsedmik — APPROVED** [review]
LGTM

**Review by LadislavVasina1 — APPROVED** [review]
ACK

**Pull request merged**
