### PR TITLE
[6.13.z] Added possibility to search for debian errata

### PR DESCRIPTION
**Pull request by vsedmik**
Manual cherry-pick of https://github.com/SatelliteQE/airgun/pull/1013

### CODE REVIEW

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k test_end_to_end

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: test_positive_filtered_errata_status_installable_param

**Comment by vsedmik** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_errata.py -k test_positive_filtered_errata_status_installable_param

**Review by dosas — COMMENTED** [review]
Thank you. LGTM

**Review by sambible — APPROVED** [review]
PRT failures are unrelated, changes are in 6.15 and test is passing there. LGTM

**Pull request merged**
