### PR TITLE
ansible collection view end entity

### PR DESCRIPTION
**Pull request by pondrejk**
wip, tests pending 
https://bugzilla.redhat.com/show_bug.cgi?id=1989989

### CODE REVIEW

**Comment by JacobCallahan** [comment]
@pondrejk any luck with this?

**Comment by pondrejk** [comment]
just for update, found out breadcrumbs not around on the collections page, I filed a Bz,  I'll see how it evolves, maybe will use a different identifier if thing won't move

**Comment by lhellebr** [comment]
Is this still current?
Maybe link the mentioned BZ here, @pondrejk?

**Comment by pondrejk** [comment]
yeah the bz is still in the new state, target unspecified, so we'll probably need to navigate without breadcrumbs 
https://bugzilla.redhat.com/show_bug.cgi?id=1989989

**Comment by pondrejk** [comment]
Closing, modeling the ansible collection list page is not currently required by any high-prio test scenario and the blocking bz for the breadcrumb issue is going to be auto-closed. We can revisit this should we need it in the future

**Pull request closed without merging**
