### PR TITLE
added properties for airgun

### PR DESCRIPTION
**Pull request by amolpati30**
i have made some small changes and added one airgun entities and views for host_new module.
below test_case is depending on given changes.

Dependent PR: https://github.com/SatelliteQE/robottelo/pull/14556

### CODE REVIEW

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 247
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : =========== 1 failed, 9 deselected, 8 warnings in 678.16s (0:11:18) ============
```

**Comment by omkarkhatavkar** [comment]
@amolpati30 Can you please resolve the conflicts here airgun/entities/host_new.py and then Run PRT.

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 249
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : =========== 1 failed, 9 deselected, 22 warnings in 659.85s (0:10:59) ===========
```

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 251
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : =========== 1 passed, 9 deselected, 24 warnings in 727.59s (0:12:07) ===========
```

**Review by omkarkhatavkar — APPROVED** [review]

**Pull request merged**
