### PR TITLE
Fix puppet-related URLs

### PR DESCRIPTION
**Pull request by vsedmik**
The puppet-related URLs changed with movement into a plugin in 7.0.

### CODE REVIEW

**Review by jameerpathan111 — APPROVED** [review]

**Comment by swadeley** [comment]
Hi

I don't see a 6.10 branch and seems to me this should not be in master before such a branch is made.

**Comment by jameerpathan111** [comment]
@swadeley you are right, we need this change for 7.0 only.

**Comment by vsedmik** [comment]
Yes, this is intended for 7.0 only

### DO NOT MERGE until 6.10 is branched!

**Review by swadeley — APPROVED** [review]
ACK

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Pull request merged**
