### PR TITLE
Rework new CV UI Search

### PR DESCRIPTION
**Pull request by sambible**
The first in a long line of PRs fleshing out functionality for the "new" CV UI page - this one is simple, just updates the PF4Search widget to have accurate locators, so that it functions properly. 

Exercised in a test in a sister PR.

### CODE REVIEW

**Review by lhellebr — APPROVED** [review]
These locators surely look better!

Can you please link the "sister PR"? If the tests pass, ACK.

**Review by vsedmik — APPROVED** [review]
The sister PR is https://github.com/SatelliteQE/robottelo/pull/11927 I guess, but the PRT fails there on something else (nav-pf-vertical).
However, these locators looks correct to me (seen at several places in Sat UI).

**Comment by omkarkhatavkar** [comment]
@sambible can you try this locally with the 6.14 or 6.13 release satellite?

**Comment by lhellebr** [comment]
I believe this PR is obsoleted by https://github.com/SatelliteQE/airgun/pull/913 which is more general. It also resolves the issue with this PR's search not actually searching (not clicking the search button).

**Review by synkd — APPROVED** [review]

**Review by lhellebr — CHANGES_REQUESTED** [review]
Fix the search to actually search please. Alternatively, close this PR in favor of the aforementioned.

**Comment by omkarkhatavkar** [comment]
@sambible Thanks for raising this PR, but all search widget thing is added in the PR https://github.com/SatelliteQE/airgun/pull/913, closing this for now.

**Pull request closed without merging**
