### PR TITLE
RHAI Inventory fix

### PR DESCRIPTION
**Pull request by quarckster**
- fixed session property;
- improved search method of `InventoryHostEntity`

### CODE REVIEW

**Comment by quarckster** [comment]
@oshtaier @abalakh please review and merge if it's ok.

**Comment by oshtaier** [comment]
any specific reason for that change? We always return table in any search that we have in our code and make actual assertion on a test level. That makes sense as sometimes you need to fetch other column values rather than name

**Comment by quarckster** [comment]
@oshtaier `InventoryAllHosts` cannot use `SearchableViewMixin`, for that [test](https://github.com/SatelliteQE/robottelo/pull/6199/files#diff-9d8bd439118c370472292e633d7d4597R70) I need to check if a host in the table.

**Comment by oshtaier** [comment]
still all search methods return table to test, so you can check on a test level whether host name is present in the table, so:
```
        view = self.navigate_to(self, "All")
        view.search.fill(host_name)
        return view.table
```
and on test level:
```
assert session.rhai_inventory.search(host_name)[0]['System Name'] == host_name
```
that approach let you check all other columns, e.g.:
```
assert session.rhai_inventory.search(host_name)[0]['Column_2_Value'] == expected_value
```

That is a common approach used all other out entities

**Comment by quarckster** [comment]
@oshtaier fixed, thank you so much for all your hard work you've done and please sorry me for my stupidity. I hope I don't disturb you a lot.

**Comment by oshtaier** [comment]
@quarckster Thank you for your patience =)

**Comment by oshtaier** [comment]
please rebase,
https://github.com/SatelliteQE/airgun/blob/master/airgun/session.py#L285

**Pull request merged**
