### PR TITLE
[6.15.z] added changes in host_new entities

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1347

changes added which will help to remove single ansible role from host.

Dependent PR: https://github.com/SatelliteQE/robottelo/pull/14556

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by omkarkhatavkar** [comment]
@amolpati30 can you please check the PRT ?

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 276
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : ========== 1 passed, 14 deselected, 29 warnings in 736.19s (0:12:16) ===========
```

**Pull request merged**
