### PR TITLE
adding ansible role as per given input...

### PR DESCRIPTION
**Pull request by amolpati30**
- I've updated the code. Previously, the role selection was hardcoded based on the locator, but now the code dynamically selects a single Ansible role based on user input.

- This update has been applied wherever the 'add_single_ansible_role' method is used in the test case.

Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16054

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
@amolpati30 Do you've any robottelo PR for this change? if not, could you run PRT here?

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k 'TestAnsibleCfgMgmt'
robottelo: 16054

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 386
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py -k TestAnsibleCfgMgmt --external-logging
Test Result : = 3 failed, 5 passed, 15 deselected, 231 warnings, 1 error in 1562.15s (0:26:02) =
```

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k 'test_positive_assign_and_remove_ansible_role_to_host or test_positive_assign_and_remove_ansible_role_to_hostgroup or test_positive_non_admin_user_access_with_usergroup or test_positive_ansible_config_report_changes_notice_and_failed_tasks_errors'
robottelo: 16054

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 391
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host or test_positive_assign_and_remove_ansible_role_to_hostgroup or test_positive_non_admin_user_access_with_usergroup or test_positive_ansible_config_report_changes_notice_and_failed_tasks_errors --external-logging
Test Result : ========= 4 passed, 10 deselected, 212 warnings in 1846.78s (0:30:46) ==========
```

**Review by Gauravtalreja1 — APPROVED** [review]

**Review by omkarkhatavkar — APPROVED** [review]

**Pull request merged**
