### PR TITLE
Cherry-picking Ansible UI fixes

### PR DESCRIPTION
**Pull request by adarshdubey-star**
Ansible UI fixes
https://github.com/SatelliteQE/airgun/pull/790

### CODE REVIEW

**Review by shweta83 — APPROVED** [review]
LGTM

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by adarshdubey-star** [comment]
The failing test case scenarios are due to the new job invocation page

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_ansible_custom_role

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_config_report_ansible

**Comment by adarshdubey-star** [comment]
The above test cases will fail because of the new job invocation page in 6.13. And the reason the whole module is not working together is an issue I have identified as the entire module is using the same worker and when it's assigning the ansible_role_id as `target_host.assign_ansible_roles(data={'ansible_role_ids': [1]})` with this line over here, there is a clash of not having the same id as 1, it will be changed when running the other test case on the same worker.

**Comment by adarshdubey-star** [comment]
Merging can be performed

**Comment by adarshdubey-star** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py -k test_positive_ansible_custom_role

**Pull request merged**
