### PR TITLE
[6.13.z] added changes in host_new entities

### PR DESCRIPTION
**Pull request by amolpati30**
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1347

changes added which will help to remove single ansible role from host.

Dependent PR: https://github.com/SatelliteQE/robottelo/pull/16096

### CODE REVIEW

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 16096

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 383
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : ========== 1 failed, 11 deselected, 21 warnings in 855.43s (0:14:15) ===========
```

**Comment by amolpati30** [comment]
ack

**Pull request merged**
