### PR TITLE
[6.15.z] Fix sattable locators

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/1544

null

### CODE REVIEW

**Comment by Satellite-QE** [comment]
trigger: test-robottelo
pytest: tests/foreman/longrun/test_oscap.py::test_positive_oscap_remediation

**Comment by pondrejk** [comment]
@lhellebr is it possible that the selected test is not present in 6.15 branch in robottelo? Maybe pick a different one for prt

**Comment by lhellebr** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py::test_positive_read_from_details_page

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 392
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_host.py::test_positive_read_from_details_page --external-logging
Test Result : ================== 1 passed, 10 warnings in 717.42s (0:11:57) ==================
```

**Pull request merged**
