### PR TITLE
Update get_register_command

### PR DESCRIPTION
**Pull request by shweta83**
Make sure Global registration form is fully loaded before filling all the values.

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 336
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ====== 2 failed, 10 passed, 834 warnings, 7 errors in 4591.55s (1:16:31) =======
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 337
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ======= 4 failed, 8 passed, 844 warnings, 7 errors in 4989.53s (1:23:09) =======
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 338
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ====== 1 failed, 11 passed, 857 warnings, 7 errors in 4510.18s (1:15:10) =======
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 339
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ================= 24 warnings, 19 errors in 204.60s (0:03:24) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 340
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ================= 24 warnings, 19 errors in 220.69s (0:03:40) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 341
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ================= 24 warnings, 19 errors in 205.93s (0:03:25) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 343
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ================= 24 warnings, 19 errors in 245.50s (0:04:05) ==================
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 344
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ================= 24 warnings, 19 errors in 198.29s (0:03:18) ==================
```

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 346
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_registration.py --external-logging
Test Result : ====== 1 failed, 17 passed, 1035 warnings, 1 error in 5883.70s (1:38:03) =======
```

**Comment by Gauravtalreja1** [comment]
PRT passed on https://github.com/SatelliteQE/robottelo/pull/15990

**Review by Gauravtalreja1 — APPROVED** [review]

**Review by LadislavVasina1 — APPROVED** [review]

**Pull request merged**
