### PR TITLE
update ansible variable matcher_value locator

### PR DESCRIPTION
**Pull request by amolpati30**
Previously, the test case was failing because it couldn’t retrieve the locator. I updated the locator to ensure it fetches the correct value when creating the Ansible variable.

### CODE REVIEW

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_ansible_role_variable_on_host

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 432
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_ansible_role_variable_on_host --external-logging
Test Result : ====== 1 failed, 10 deselected, 21 warnings, 1 error in 778.61s (0:12:58) ======
```

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_ansible_role_variable_on_host

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 433
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_ansible_role_variable_on_host --external-logging
Test Result : ========== 1 passed, 10 deselected, 22 warnings in 802.62s (0:13:22) ===========
```

**Review by shweta83 — APPROVED** [review]
Ack

**Review by shubhamsg199 — APPROVED** [review]

**Pull request merged**
