### PR TITLE
added changes in host_new entities

### PR DESCRIPTION
**Pull request by amolpati30**
changes added which will help to remove single ansible role from host.

Dependent PR: https://github.com/SatelliteQE/robottelo/pull/14556

### CODE REVIEW

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
airgun: 14556

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
airgun: 14556

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 258
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : ========== 1 failed, 14 deselected, 23 warnings in 1458.62s (0:24:18) ==========
```

**Comment by amolpati30** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host
robottelo: 14556

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 259
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_ansible.py::TestAnsibleCfgMgmt -k test_positive_assign_and_remove_ansible_role_to_host --external-logging
Test Result : ========== 1 passed, 14 deselected, 29 warnings in 785.52s (0:13:05) ===========
```

**Review by omkarkhatavkar — APPROVED** [review]

**Pull request merged**
