### PR TITLE
6.11.Z: Ansible UI fixes (#790)

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
https://github.com/SatelliteQE/airgun/pull/818

### CODE REVIEW

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by omkarkhatavkar** [comment]
@adarshdubey-star can you please take a look at the failures

**Comment by adarshdubey-star** [comment]
I would request you to close this one as I  need to update the locators for 6.11, will be doing it later on.

**Pull request closed without merging**
