### PR TITLE
Added search for ldap auth

### PR DESCRIPTION
**Pull request by ntkathole**
Fixes https://github.com/SatelliteQE/robottelo/issues/6687

### CODE REVIEW

**Comment by oshtaier** [comment]
both `read_table_row` and `search` should be removed. Let's me find time and provide examples. Basically, `Table` widget and our basic `search` should already handle that situation. I think you agree that it will be really bad idea to add same two methods in other 50 modules.

**Comment by oshtaier** [comment]
Maybe LDAP entity doesn't have welcome screen (https://github.com/SatelliteQE/airgun/blob/master/airgun/views/common.py#L407). Hmm

**Comment by oshtaier** [comment]
Anyway, I feel proposed solution is a little bit redundant. Maybe, it will be better to stop at that moment on:
```
    def read_table_row(self, entity_name):
        """Read values for corresponding table row from LDAP Authentication
        title page. Return None in case row is not present in the table
        """
        view = self.navigate_to(self, 'All')
        try:
            row_value = view.table.row(name=entity_name).read()
        except RowNotFound, NoSuchElementException:
            row_value = None
        return row_value
```
It is not perfect solution, but not the worst and better will require some time for investigation

**Comment by ntkathole** [comment]
@oshtaier Thanks. It works perfect.

**Comment by oshtaier** [comment]
It just can catch some other invalid situation =), but we use solution very specifically, so it is not big problem with that 'None'

**Pull request merged**
