### PR TITLE
[cherry-pick 6.7.z] Add RH Cloud - Inventory support (#500)

### PR DESCRIPTION
**Pull request by mirekdlugosz**
Cherry-pick #500 into `6.7.z`.

This is part of larger effort of running inventory upload tests on 6.7.z snaps.

Test result: see https://github.com/SatelliteQE/robottelo/pull/7983

### CODE REVIEW

**Review by omkarkhatavkar — APPROVED** [review]
ACK

**Review by lhellebr — COMMENTED** [review]
I'd ACK but Travis isn't happy.

**Comment by mirekdlugosz** [comment]
@lhellebr was it ever happy? 
It complains about view.activationkey docstring, and I don't touch that in this PR.

**Review by lhellebr — APPROVED** [review]
ACK

**Pull request merged**
