### PR TITLE
wait for a dashboard card to load

### PR DESCRIPTION
**Pull request by pondrejk**
similar to https://github.com/SatelliteQE/airgun/pull/1555

### CODE REVIEW

**Comment by pondrejk** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_remoteexecution.py -k test_positive_run_default_job_template
airgun: 1556

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 402
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_remoteexecution.py -k test_positive_run_default_job_template --external-logging
Test Result : ========== 1 passed, 7 deselected, 22 warnings in 1032.75s (0:17:12) ===========
```

**Review by sambible — APPROVED** [review]
I'm not as opposed to hard sleeps as some other reviewers, it can be an effective tool to resolve very unfortunate disconnects between PRT/Local runs and CI. 

Approving this, and will also be approving https://github.com/SatelliteQE/airgun/pull/1555

**Review by LadislavVasina1 — APPROVED** [review]
ACK, I agree with @sambible comment

**Pull request merged**
