### PR TITLE
Update Activation Keys OUIA ID

### PR DESCRIPTION
**Pull request by shweta83**
Changes from https://github.com/Katello/katello/pull/10590

### CODE REVIEW

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_registration.py

**Review by Gauravtalreja1 — APPROVED** [review]

**Comment by shweta83** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_host.py -k test_global_registration_token_restriction

**Review by lhellebr — APPROVED** [review]
Simple enough, LGTM

**Comment by shweta83** [comment]
Can we get this PR merged? The failures are unrelated to this change and failing only on stream because of another locator.

**Comment by lhellebr** [comment]
So we merged to master although it fails on stream? That doesn't make sense to me, please reconsider.

**Pull request merged**
