### PR TITLE
redhat_repositories search box & button xpath, add wait_for in search

### PR DESCRIPTION
**Pull request by vijaysawant**
**Problem:** `Search box` and `search button` for `Content > Red Hat Repositories` page were not found, rather script was selecting left pannel search box. Apart from this, test was not waiting for page to load before searching on `Red Hat Repositories` page.

**Solution:** The updated `XPaths` and added `wait_for` method before searching any rh repositories.

**Note:** 
Correspondig Robottelo PR https://github.com/SatelliteQE/robottelo/pull/14673

### CODE REVIEW

**Review by vsedmik — APPROVED** [review]
LGTM

**Comment by shweta83** [comment]
you can run prt here as well.

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 240
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo --external-logging
Test Result : =========== 32 deselected, 3 warnings, 1 error in 749.05s (0:12:29) ============
```

**Comment by vijaysawant** [comment]
Airgun PRT failed due to fixture "module_entitlement_manifest_org"
**Error Message**
```
failed on setup with "requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://ip-10-0-217-241.rhos-01.prod.psi.rdu2.redhat.com/katello/api/organizations/3/simple_content_access/disable"
```
Raising PR for above error message and it will applicable for `stream`.

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 241
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo --external-logging
Test Result : ================= 32 deselected, 3 warnings, 1 error in 48.79s =================
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo
env:
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: 'ystream'
```

**Comment by vijaysawant** [comment]
```
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo
env:
    ROBOTTELO_server__deploy_arguments__deploy_sat_version: '6.15'
    ROBOTTELO_server__deploy_arguments__deploy_snap_version: '13.0'
```

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 242
Build Status: SUCCESS
PRT Comment: pytest tests/foreman/ui/test_repository.py -k test_positive_delete_rhel_repo --external-logging
Test Result : =========== 1 passed, 32 deselected, 9 warnings in 871.03s (0:14:31) ===========
```

**Pull request merged**
