### PR TITLE
[6.11.z] Cherry-picking Ansible UI fixes

### PR DESCRIPTION
**Pull request by Satellite-QE**
Cherrypick of PR: https://github.com/SatelliteQE/airgun/pull/815

Ansible UI Fixes
https://github.com/SatelliteQE/airgun/pull/790

### CODE REVIEW

**Comment by adarshdubey-star** [comment]
> @adarshdubey-star is the PRT failure here a blocker to merge?

Yes, I am assuming the locators are a bit different with 6.11 sat need to check that again.

**Comment by jyejare** [comment]
Ping @adarshdubey-star !!

**Comment by Gauravtalreja1** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by devendra104** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_ansible.py

**Comment by omkarkhatavkar** [comment]
Somehow this is taking a lot of time to fix the cherrypicking, and creating new PR for this.

**Pull request closed without merging**
