### PR TITLE
New job invocation details page

### PR DESCRIPTION
**Pull request by pnovotny**
New view and navigation was added for the first part of the new job invocation details page.

This feature is still an experimantal feature/tech preview and it is not yet fully completed.
Other content will be added in later phases.

### CODE REVIEW

**Review by pondrejk — APPROVED** [review]

**Review by lhellebr — APPROVED** [review]
ACK once PRT passes repeatedly (to avoid race conditions)

**Comment by pnovotny** [comment]
I am trying to solve a problem, where the new details page doesn't load completely when running the PRT in our Selenium Grid w/ Chrome. 
The page is only partially loaded like this:
job-inv-not-fully-loaded

But it loads fine when running the test locally w/ Firefox or Chrome:
job-inv-fully-loaded

**Comment by pnovotny** [comment]
PRT on https://github.com/SatelliteQE/robottelo/pull/15980 passed (twice).
@pondrejk @lhellebr Can we pls merge?

**Review by LadislavVasina1 — APPROVED** [review]
ACK

**Pull request merged**
