### PR TITLE
update the logic for install package using katello-agent

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
### PR Description

- When we install the package using Katello-Agent then Conte Host Task Details page populated, this view needs to be associated with action function. 
- Remove not required logic 

### Test Result 
Please see the PR https://github.com/SatelliteQE/robottelo/pull/7947

### CODE REVIEW

**Review by mirekdlugosz — APPROVED** [review]
Seems with this test, we lose ability to click "Apply selected". Which would pop up a dialog and apply default method, I guess?
Since your test is the only one that actually uses this method, I'm not particularly concerned about this. 

ACK

**Comment by omkarkhatavkar** [comment]
> I'm not particularly concerned about this.

You are correct are going to lose that functionality, seems there is not test which uses that yet. Hence Just to make things simpler I removed. We should add it in case any test using the 'apply selected'

**Comment by omkarkhatavkar** [comment]
Incase anyone looking for Travis failure it is unrelated to PR, this is an existing issue.

**Review by lhellebr — APPROVED** [review]
LGTM

**Pull request merged**
