### PR TITLE
Run Autocherrypick on merged PRs

### PR DESCRIPTION
**Pull request by jyejare**
$subject

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo

**Comment by Gauravtalreja1** [comment]
@jyejare can we close this in favor of this duplicate PR https://github.com/SatelliteQE/airgun/pull/849 ?

**Comment by omkarkhatavkar** [comment]
@jyejare I see some conflicts, can you please take a look at this?

**Comment by jyejare** [comment]
@omkarkhatavkar will do look.

**Comment by jyejare** [comment]
Right @Gauravtalreja1 , Looks like its a duplicate of https://github.com/SatelliteQE/airgun/pull/849 , Closing this PR.

**Pull request closed without merging**
