### PR TITLE
Add debian repository to views

### PR DESCRIPTION
**Pull request by dosas**
to enable debian repo testing for orcharhino.

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by JacobCallahan** [comment]
@dosas since we can't really test this (aside from upstream builds), can you provide some examples of your use?

**Comment by dosas** [comment]
@JacobCallahan I understand. 
The only example I have is from a robottelo test that is not upstream:
```
        session.repository.create(
            product_name,
            {
                'name': repo_name,
                'repo_type': REPO_TYPE['deb'],  # "deb"
                'repo_content.upstream_url': repo.url,
                'repo_content.releases': deb_releases,
                'repo_content.errata_url': repo.errata_url,
            },
        )
```

**Comment by dosas** [comment]
Any news on this?

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py -k test_positive_create_in_different_orgs

**Comment by omkarkhatavkar** [comment]
These failures are unrelated to this PR

**Comment by omkarkhatavkar** [comment]
@vijaysawant @vsedmik @sambible @ColeHiggins2 Anyone of you can confirm the Debian Repository.

**Comment by ogajduse** [comment]
Update: Phoenix team pinged in their team channel.

**Comment by dosas** [comment]
Any news from the phoenix team?

**Comment by vijaysawant** [comment]
trigger: test-robottelo
pytest: tests/foreman/ui/test_repository.py

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 219
Build Status: UNSTABLE
PRT Comment: pytest tests/foreman/ui/test_repository.py
Test Result : =========================== short test summary info ============================
```

**Review by sambible — APPROVED** [review]
Failure seems unrelated. This change would not result in any problems, and seems fine.

**Review by omkarkhatavkar — APPROVED** [review]

**Review by vsedmik — APPROVED** [review]

**Comment by dosas** [comment]
@sambible Thanks for merging this. How do I get these changes into 6.15.z, do I have to create a separate PR?

**Comment by vsedmik** [comment]
@dosas The standard/easiest way is just adding `CherryPick` and your desired `6.<Y>.z` labels before merging, so it gets auto cherry-picked. Since this PR is merged already I would suggest raising a new PR against the `6.15.z` branch, cherry-picking your 03a97c8d67ee5733e05e8dc488d059daaa8f4ea4 commit.

**Comment by dosas** [comment]
@vsedmik Thanks, but the problem is I cannot add labels.

I will create another PR

**Pull request merged**
