### PR TITLE
This dummy pr please do not merge this

### PR DESCRIPTION
**Pull request by omkarkhatavkar**

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: tests/foreman/api/test_ansible.py

**Comment by swadeley** [comment]
s/no merge/not merge/

**Comment by omkarkhatavkar** [comment]
PRT looks fine now. Now supported from Airgun

**Pull request closed without merging**
